### ISSUE TITLE
Strange Behaviour

### ISSUE THREAD

**Issue by ygtc** [jneilliii/OctoPrint-TabOrder#18]
Hi, i like this plugin and i am always using.In these days i noticed strange behaviour.

When i open octoprint or restart octoprint taborder seen like photo1.

![taborder1](https://user-images.githubusercontent.com/39675823/46233944-47ef6600-c37d-11e8-94f4-85a947db4426.jpg)

After i click wrench icon top-right corner(config) then close,taborder start works normally again.

![taborder2](https://user-images.githubusercontent.com/39675823/46233951-576eaf00-c37d-11e8-92e7-9cbdf419530f.jpg)

Is that a problem or glitch maybe bug :D 

I just noticed that and i want to ask

**Comment by jneilliii** [comment]
Yeah, I think that has to do with the underlying bootstrap tabs.  OctoPrint core programming is handling the stacking of those tabs under the top right list on your initial load.  Not sure if there is a way for me to work around that, but I'll see if I can figure something out.

**Comment by ygtc** [comment]
maybe it is only about processing power? I mean maybe orange pi which is better hardware than raspi3 doesn't see this behaviour.I don't know actually if anything i can to help let me know.

**Comment by ygtc** [comment]
and also i can share other my observations about this plugin. Like order issue and other plugins corrupt taborder's stable working

**Comment by otherguy** [comment]
I have the same issue on Safari and Chrome. Resizing the window after the page is fully loaded, solves it. You probably need to trigger a resize event from JS after the page is done loading completely (not just DOM). The reason is that before the labels are hidden, the max number of displayed elements is calculated.

**Comment by jneilliii** [comment]
So I'm still unable to reproduce this issue on my end.  @ygtc  or @otherguy, could you please provide a screenshot of your Tab Order settings as well as the plugins you have installed/enabled in OctoPrint? Also the exact steps to reproduce the behavior,

**Comment by otherguy** [comment]
Not right now but it also happens without any plugins installed. Reproducing it is simple: use only font awesome icons, disable labels and reload. make sure that before reloading, the browser is sized so that not all tabs with their label texts fot on the screen.

while octoprint is reloading, the labels are still visible, along with the font awesome icons. when loading is finished, the labels disappear and all tab icons would fit on the screen - but since a resize event is not triggered, only the original icons show up.

**Comment by jneilliii** [comment]
Thanks @otherguy, I'm able to reproduce with those steps of a reduced window browser. I'm going to have to look through octoprint's code to see which element I need to trigger the resize action on, because it's a specific element that is doing that stacking in bootstrap I would suspect.

**Comment by otherguy** [comment]
I suspect bootstrap handles that. `window.trigger(“resize”)` (pseudocode) should be enough.

**Comment by jneilliii** [comment]
Yeah, I ended up testing and using the jQuery resize event seems to work from within developer console.  I'm testing an update to the plugin now to see when to trigger that to resolve.  Will have an updated version by the end of the day probably.

**Comment by jneilliii** [comment]
Got it first try.  Seems to be working for me fine now, so I pushed an updated version 0.5.1.  Force check in software update and you should be able to get it.

**Comment by otherguy** [comment]
Great! Looks good and works just fine 👍 Thanks for fixing it 🙂 

I look at it mostly on my 13" screen -- if you use a big display that explains why you didn't notice it.

Not to push my luck but would you also consider https://github.com/jneilliii/OctoPrint-TabOrder/issues/21 ?

Thanks and have a happy new year!

**Comment by ygtc** [comment]
Problem solved for me also!! Thanks for fixing it :smile: 

Keep up to great work m8!! :+1:
