### ISSUE TITLE
Update to Font Awesome 5

### ISSUE THREAD

**Issue by otherguy** [jneilliii/OctoPrint-TabOrder#21]
Would you consider updating to [Font Awesome 5](https://fontawesome.com/start)? They have a ton of new icons that would be perfectly suited for the tabs!

**Comment by jneilliii** [comment]
Thanks for the push. Was holding back on this due to the change in base class names (fa becoming fas) but figured I could make that part of the icon field as well and not hard-code the base class. It will attempt to add the base class to the configured icons, but potentially can break some icons; those will have to be re-configured in settings.

**Comment by otherguy** [comment]
Awesome, thanks 😄 Works great, even with the `fab` and `far` classes. I love it! `fab-youtube` for the live streaming plugin is perfect!

Thank you again and I hope you have a great new year!
